### PR TITLE
fix: false positives for custom-element with svelte v3 in `svelte/valid-compile`

### LINKED ISSUE #602: False Positive for 'customElement: true'.
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.52.0

### What version of `eslint-plugin-svelte` are you using?

2.34.0

### What did you do?

<details>
<summary>Configuration</summary>

```
module.exports = {
	root: true,
	parser: '@typescript-eslint/parser',
	extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended', 'prettier', 'plugin:svelte/recommended'],
	plugins: ['@typescript-eslint'],
	ignorePatterns: ['*.cjs'],
	overrides: [
		{
			files: ['*.svelte'],
			parser: 'svelte-eslint-parser',
			parserOptions: {
				parser: '@typescript-eslint/parser'
			}
		}
	],
	parserOptions: {
		sourceType: 'module',
		ecmaVersion: 2020,
		project: './tsconfig.json',
		extraFileExtensions: ['.svelte']
	},
	env: {
		browser: true,
		es2017: true,
		node: true
	},
	rules: {
		'@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
		'@typescript-eslint/no-explicit-any': 'off',
		'no-prototype-builtins': 'off',
		// 'svelte/valid-compile':'off'
	},
	settings: {
		svelte: {
			compileOptions: {
				customElement: true
			}
		}
	}
};

```
</details>

```svelte
<svelte:options tag="iron-remote-gui"/>

<script lang="ts">
    import {onMount} from 'svelte';
...
</script>
...

```

### What did you expect to happen?

I expect eslint throw no error with run `npx eslint src/**`

### What actually happened?

```
> npx eslint src/**


C:\Users\jou\code\IronRDP\web-client\iron-remote-gui\src\iron-remote-gui.svelte
  1:17  error  The 'tag' option is used when generating a custom element. Did you forget the 'customElement: true' compile option?(missing-custom-element-compile-options)  svelte/valid-compile

✖ 1 problem (1 error, 0 warnings)

```

### Link to **GitHub Repo** with Minimal Reproducible Example

[IronRDP](https://github.com/Devolutions/IronRDP/pull/258/files#diff-c24a4bae4bdc3978d2fdbe7729ffeb77a49509e8405d8dc2d966db2df8306e58)

inside the ./web-client/iron-remote-gui, one can try remove the
```
svelte/valid-compile': 'off'
```
to reproduce this problem
### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by ota-meshi**
fixes #602

### CODE REVIEW

File: src/shared/svelte-compile-warns/index.ts [hunk 1]
```diff
@@ -401,17 +401,37 @@ function* transformScripts(context: RuleContext, text: string) {
...
+): {
 	warnings: Warning[];
 	kind: 'warn' | 'error';
 } {
 	try {
 		const result = compiler.compile(code, {
 			generate: false,
-			...(semver.satisfies(compiler.VERSION, '>=4.0.0-0') ? { customElement: true } : {})
+			...(semver.satisfies(compiler.VERSION, '>=4.0.0-0')
+				? { customElement: true }
```
Comment (baseballyama) [inline src/shared/svelte-compile-warns/index.ts:431]: [ask]

Why always we can set `{ customElement: true }` if Svelte version is 4?

Comment (ota-meshi) [reply src/shared/svelte-compile-warns/index.ts:431]: In v3, if `customElement:true` is set, a warning will be returned if `<svelte:options tag>` is missing, but in v4, there will be no warning even if `<svelte:options customElement>` is missing.

**Review by baseballyama — APPROVED** [review]
